## 기존 import

In [ ]:
import pandas as pd

compet_1  = pd.read_csv("/content/drive/MyDrive/과제3/경쟁사이용 - 복사본.txt", sep = ",", encoding = "cp949")
demo_1    = pd.read_csv("/content/drive/MyDrive/과제3/CUSTDEMO.txt", sep = ",", encoding = "cp949")
prodpur_1 = pd.read_csv("/content/drive/MyDrive/과제3/구매상품TR - 복사본.txt", sep = ",", encoding = "cp949")
member_1  = pd.read_csv("/content/drive/MyDrive/과제3/멤버십여부 - 복사본.txt", sep = ",", encoding = "cp949")
prodcl_1  = pd.read_csv("/content/drive/MyDrive/과제3/상품분류 - 복사본.txt", sep = ",", encoding = "cp949")
channel_1 = pd.read_csv("/content/drive/MyDrive/과제3/채널이용 - 복사본.txt", sep = ",", encoding = "cp949")

In [ ]:
final_t= pd.read_csv("/content/drive/MyDrive/과제3/upperclass_final.txt", sep = ",")
final_t= final_t[['소분류코드',"소분류명"]]

final_list= pd.read_csv("/content/drive/MyDrive/과제3/final_store_list.csv", sep = ",")
final_list = final_list.iloc[:,1:]

final_df = pd.read_csv("/content/drive/MyDrive/과제3/final_df_purchase.csv", sep = ",")
final_df = final_df.iloc[:,1:]

f_list = pd.read_excel("/content/drive/MyDrive/과제3/상품분류_재.xlsx")
f_list = f_list[["소분류코드",'중분류명_재','대분류명_재']]

In [ ]:
# demo 데이터 전처리
demo_1["고객번호"] = demo_1["고객번호"].astype("str")
demo_1= demo_1[["고객번호","성별","연령대"]]

#칼럼분류 
final_df = final_df[["제휴사",'소분류코드','고객번호','점포코드','구매시간','구매금액','년도','월','분기']]

#타입바꾸기
final_df["고객번호"] = final_df["고객번호"].astype("str")
# final_df

final_t= final_t[['소분류코드',"소분류명"]]
# final_t

## 기존 pd.merge

In [ ]:
# 최종 기존 데이터 fd_f 

import pandas as pd
d_f = pd.DataFrame()
d_f = pd.merge(demo_1, final_df, on ='고객번호')
d_flist = pd.merge(d_f, f_list, on ='소분류코드')
d_list = pd.merge(d_flist, final_list, on ='점포코드')
fd_f = pd.merge(final_t, d_list, on ='소분류코드')
fd_f

,소분류코드,소분류명,고객번호,성별,연령대,제휴사,점포코드,구매시간,구매금액,년도,월,분기,중분류명_재,대분류명_재,시군구
0,A010101,위생세제,1,M,60세이상,A,A12,15,9500,2014,2,1st,위생용품,일상용품,강남구
1,A010101,위생세제,1,M,60세이상,A,A12,15,5000,2014,9,3rd,위생용품,일상용품,강남구
2,A010101,위생세제,1,M,60세이상,A,A12,11,19810,2014,1,1st,위생용품,일상용품,강남구
3,A010101,위생세제,1,M,60세이상,A,A12,12,1000,2015,3,5th,위생용품,일상용품,강남구
4,A010101,위생세제,1,M,60세이상,A,A12,17,6800,2015,11,8th,위생용품,일상용품,강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8336524,D080401,일반네일/케어류,16424,M,25세~29세,D,D8,19,8000,2015,8,7th,미용용품,일상용품,중랑구
8336525,D080401,일반네일/케어류,18977,F,20세~24세,D,D8,19,55000,2014,8,3rd,미용용품,일상용품,중랑구
8336526,D080401,일반네일/케어류,18977,F,20세~24세,D,D8,12,3700,2015,6,6th,미용용품,일상용품,중랑구
8336527,D080401,일반네일/케어류,18977,F,20세~24세,D,D8,12,12000,2015,6,6th,미용용품,일상용품,중랑구
8336528,D080401,일반네일/케어류,18986,F,20세~24세,D,D8,14,13500,2015,9,7th,미용용품,일상용품,중랑구

### 1.대분류명 인코딩

In [ ]:
fd_f['대분류명_재'].unique()

array(['일상용품', '행사상품', '신선식품', '가공식품', '기타', '패션의류/잡화', '유아용품', '스포츠/레저',
       '디지털/가전', '교육/문화용품', '명품', '가구/인테리어', '교육/문화', nan, '행사식품', '행사삭품',
       '명퓸', '신석식품', '유아식품'], dtype=object)

In [ ]:
item=['일상용품', '행사상품', '신선식품', '가공식품', '기타', '패션의류/잡화', '유아용품', '스포츠/레저','디지털/가전', '교육/문화용품', '명품', '가구/인테리어', '교육/문화', '행사식품', '행사삭품','명퓸', '신석식품', '유아식품']

In [ ]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
encoder.fit(item)
labels = encoder.transform(item)

print('인코딩 변환 값:', labels)
print('인코딩 클래스:',encoder.classes_)

인코딩 변환 값: [13 16 10  0  4 14 12  8  5  3  6  1  2 17 15  7  9 11]
인코딩 클래스: ['가공식품' '가구/인테리어' '교육/문화' '교육/문화용품' '기타' '디지털/가전' '명품' '명퓸' '스포츠/레저'
 '신석식품' '신선식품' '유아식품' '유아용품' '일상용품' '패션의류/잡화' '행사삭품' '행사상품' '행사식품']

In [ ]:
import pandas as pd
df = pd.DataFrame(labels)
df.columns=['인코딩']
# pd.get_dummies(df)

labels =fd_f['대분류명_재'].unique()
sd = pd.DataFrame(labels)
sd.columns=['대분류명_재']

df= pd.concat([sd,df],axis=1)
df

     대분류명_재   인코딩
0      일상용품  13.0
1      행사상품  16.0
2      신선식품  10.0
3      가공식품   0.0
4        기타   4.0
5   패션의류/잡화  14.0
6      유아용품  12.0
7    스포츠/레저   8.0
8    디지털/가전   5.0
9   교육/문화용품   3.0
10       명품   6.0
11  가구/인테리어   1.0
12    교육/문화   2.0
13      NaN  17.0
14     행사식품  15.0
15     행사삭품   7.0
16       명퓸   9.0
17     신석식품  11.0
18     유아식품   NaN

In [ ]:
#결측치 확인
df.isnull().sum()

대분류명_재    1
인코딩       1
dtype: int64

In [ ]:

#결측치 fillna 하기기
df = df.fillna(18.0)
df.isnull().sum()

대분류명_재    0
인코딩       0
dtype: int64

In [ ]:
df

     대분류명_재   인코딩
0      일상용품  13.0
1      행사상품  16.0
2      신선식품  10.0
3      가공식품   0.0
4        기타   4.0
5   패션의류/잡화  14.0
6      유아용품  12.0
7    스포츠/레저   8.0
8    디지털/가전   5.0
9   교육/문화용품   3.0
10       명품   6.0
11  가구/인테리어   1.0
12    교육/문화   2.0
13     18.0  17.0
14     행사식품  15.0
15     행사삭품   7.0
16       명퓸   9.0
17     신석식품  11.0
18     유아식품  18.0

In [ ]:
# 기존 데이터에 merge함.

fd_f_1 = pd.merge(fd_f, df, on ='대분류명_재')
fd_f_1

,소분류코드,소분류명,고객번호,성별,연령대,제휴사,점포코드,구매시간,구매금액,년도,월,분기,중분류명_재,대분류명_재,시군구,인코딩
0,A010101,위생세제,1,M,60세이상,A,A12,15,9500,2014,2,1st,위생용품,일상용품,강남구,13.0
1,A010101,위생세제,1,M,60세이상,A,A12,15,5000,2014,9,3rd,위생용품,일상용품,강남구,13.0
2,A010101,위생세제,1,M,60세이상,A,A12,11,19810,2014,1,1st,위생용품,일상용품,강남구,13.0
3,A010101,위생세제,1,M,60세이상,A,A12,12,1000,2015,3,5th,위생용품,일상용품,강남구,13.0
4,A010101,위생세제,1,M,60세이상,A,A12,17,6800,2015,11,8th,위생용품,일상용품,강남구,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8288904,C130404,유아음료,17973,F,55세~59세,C,C114,12,5580,2015,2,5th,영유아식품,유아식품,양천구,18.0
8288905,C130404,유아음료,17973,F,55세~59세,C,C114,20,2790,2015,4,6th,영유아식품,유아식품,양천구,18.0
8288906,C130404,유아음료,17973,F,55세~59세,C,C114,19,5580,2015,3,5th,영유아식품,유아식품,양천구,18.0
8288907,C130404,유아음료,17973,F,55세~59세,C,C114,11,2800,2015,4,6th,영유아식품,유아식품,양천구,18.0
8288908,C130404,유아음료,17973,F,55세~59세,C,C114,19,5580,2015,4,6th,영유아식품,유아식품,양천구,18.0

In [ ]:
# fd_f_1 데이터를 분기별로 나눔
d_1 = fd_f_1.query("분기 == '1st'")
d_2 = fd_f_1.query("분기 == '2nd'")
d_3 = fd_f_1.query("분기 == '3rd'")
d_4 = fd_f_1.query("분기 == '4th'")
d_5 = fd_f_1.query("분기 == '5th'")
d_6 = fd_f_1.query("분기 == '6th'")
d_7 = fd_f_1.query("분기 == '7th'")
d_8 = fd_f_1.query("분기 == '8th'")
# d_1

In [ ]:

# 점포별, 대분류명별, (대분류명 인코딩)한거 카운트 하기
d_1i=d_1.groupby(["점포코드",'인코딩'])[['대분류명_재']].count().reset_index()
d_2i=d_2.groupby(["점포코드",'인코딩'])[['대분류명_재']].count().reset_index()
d_3i=d_3.groupby(["점포코드",'인코딩'])[['대분류명_재']].count().reset_index()
d_4i=d_4.groupby(["점포코드",'인코딩'])[['대분류명_재']].count().reset_index()
d_5i=d_5.groupby(["점포코드",'인코딩'])[['대분류명_재']].count().reset_index()
d_6i=d_6.groupby(["점포코드",'인코딩'])[['대분류명_재']].count().reset_index()
d_7i=d_7.groupby(["점포코드",'인코딩'])[['대분류명_재']].count().reset_index()
d_8i=d_8.groupby(["점포코드",'인코딩'])[['대분류명_재']].count().reset_index()
d_1i

     점포코드   인코딩  대분류명_재
0      A1   0.0   15984
1      A1   1.0     535
2      A1   3.0       2
3      A1   5.0     584
4      A1   6.0    1096
...   ...   ...     ...
1253   D8   0.0      98
1254   D8   3.0       1
1255   D8   5.0       2
1256   D8  13.0      43
1257   D8  14.0       1

[1258 rows x 3 columns]

In [ ]:
#인코딩 결과를 점포별로 (max) 랭킹 찾기기 
d_1i['rank'] = d_1i.groupby(["점포코드"])[['대분류명_재']].rank(method='max', ascending=False)
d_2i['rank'] = d_2i.groupby(["점포코드"])[['대분류명_재']].rank(method='max', ascending=False)
d_3i['rank'] = d_3i.groupby(["점포코드"])[['대분류명_재']].rank(method='max', ascending=False)
d_4i['rank'] = d_4i.groupby(["점포코드"])[['대분류명_재']].rank(method='max', ascending=False)
d_5i['rank'] = d_5i.groupby(["점포코드"])[['대분류명_재']].rank(method='max', ascending=False)
d_6i['rank'] = d_6i.groupby(["점포코드"])[['대분류명_재']].rank(method='max', ascending=False)
d_7i['rank'] = d_7i.groupby(["점포코드"])[['대분류명_재']].rank(method='max', ascending=False)
d_8i['rank'] = d_8i.groupby(["점포코드"])[['대분류명_재']].rank(method='max', ascending=False)

#### 대분류명 점포별 최다판매 1위 구하기

In [ ]:
# 각 분기별 점포별 랭킹 1위만 모으기기
d_1i =d_1i[d_1i['rank']==1.0].iloc[:,:2]
d_2i =d_2i[d_2i['rank']==1.0].iloc[:,:2]
d_3i =d_3i[d_3i['rank']==1.0].iloc[:,:2]
d_4i =d_4i[d_4i['rank']==1.0].iloc[:,:2]
d_5i =d_5i[d_5i['rank']==1.0].iloc[:,:2]
d_6i =d_6i[d_6i['rank']==1.0].iloc[:,:2]
d_7i =d_7i[d_7i['rank']==1.0].iloc[:,:2]
d_8i =d_8i[d_8i['rank']==1.0].iloc[:,:2]
d_8i

     점포코드   인코딩
0      A1   0.0
11    A12   0.0
22     A2   0.0
33    A20   0.0
43    A24   0.0
...   ...   ...
1204   D4   0.0
1211   D5  13.0
1217   D6  13.0
1222   D7  13.0
1225   D8  13.0

[163 rows x 2 columns]

In [ ]:
# 각 분기별 랭킹 1위 대분류명을 바꾸기기
d_1i = d_1i.rename(columns={'인코딩':'대인코딩_1'})
d_2i = d_2i.rename(columns={'인코딩':'대인코딩_2'})
d_3i = d_3i.rename(columns={'인코딩':'대인코딩_3'})
d_4i = d_4i.rename(columns={'인코딩':'대인코딩_4'})
d_5i = d_5i.rename(columns={'인코딩':'대인코딩_5'})
d_6i = d_6i.rename(columns={'인코딩':'대인코딩_6'})
d_7i = d_7i.rename(columns={'인코딩':'대인코딩_7'})
d_8i = d_8i.rename(columns={'인코딩':'대인코딩_8'})

#### < 최종 점포별 분기별 대분류명 >

In [ ]:
#분기별로 점포코드별 대분류명을 모으기기
import pandas as pd
g_1= pd.merge(d_1i, d_2i, on ='점포코드')
g_1= pd.merge(g_1, d_3i, on ='점포코드')
g_1= pd.merge(g_1, d_4i, on ='점포코드')
g_1= pd.merge(g_1, d_5i, on ='점포코드')
g_1= pd.merge(g_1, d_6i, on ='점포코드')
g_1= pd.merge(g_1, d_7i, on ='점포코드')
g_1= pd.merge(g_1, d_8i, on ='점포코드')
g_1

    점포코드  대인코딩_1  대인코딩_2  대인코딩_3  대인코딩_4  대인코딩_5  대인코딩_6  대인코딩_7  대인코딩_8
0     A1     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
1    A12     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
2     A2     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
3    A20     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
4    A24     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
..   ...     ...     ...     ...     ...     ...     ...     ...     ...
158   D4     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0
159   D5    13.0    13.0    13.0    13.0    13.0     0.0     0.0    13.0
160   D6     0.0     0.0    13.0    13.0    13.0    13.0    13.0    13.0
161   D7     0.0     0.0    13.0    13.0    13.0    13.0    13.0    13.0
162   D8     0.0    13.0    13.0    13.0    13.0    13.0    13.0    13.0

[163 rows x 9 columns]

In [ ]:
g_1.to_csv("최다판매대분류(2).csv", index = False)

In [ ]:
# # 점포별, 대분류명별, (대분류명 인코딩)한거 카운트 하기
# d_1i=d_1.groupby(["점포코드",'대분류명_재'])[['인코딩']].count().reset_index()
# d_2i=d_2.groupby(["점포코드",'대분류명_재'])[['인코딩']].count().reset_index()
# d_3i=d_3.groupby(["점포코드",'대분류명_재'])[['인코딩']].count().reset_index()
# d_4i=d_4.groupby(["점포코드",'대분류명_재'])[['인코딩']].count().reset_index()
# d_5i=d_5.groupby(["점포코드",'대분류명_재'])[['인코딩']].count().reset_index()
# d_6i=d_6.groupby(["점포코드",'대분류명_재'])[['인코딩']].count().reset_index()
# d_7i=d_7.groupby(["점포코드",'대분류명_재'])[['인코딩']].count().reset_index()
# d_8i=d_8.groupby(["점포코드",'대분류명_재'])[['인코딩']].count().reset_index()
# d_1i

In [ ]:
# #인코딩 결과를 점포별로 (max) 랭킹 찾기기 
# d_1i['rank'] = d_1i.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_2i['rank'] = d_2i.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_3i['rank'] = d_3i.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_4i['rank'] = d_4i.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_5i['rank'] = d_5i.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_6i['rank'] = d_6i.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_7i['rank'] = d_7i.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_8i['rank'] = d_8i.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)

### 2.중분류명 인코딩

In [ ]:
fd_f['중분류명_재'].unique()

array(['위생용품', '미용용품', '생활용품', '기타행사', '축산물', '축산가공', '유제품/아이스크림', '과자류',
       '유기농', '농산물', '농산가공', '식품행사', '수산물', '수산가공', '냉동식품', '외식', '빵류/떡류',
       '가공식품_기타', '기타', '커피/차류', '음료류', '조미료', '건강식품', '주류', '액세서리/잡화',
       '모자', '패션의류/잡화_기타', '가방', '신발', '유아동의류', '영유아용품', '의류행사', '영유아의류',
       '의류', '언더웨어', '스포츠의류/신발/잡화', '골프용품', '음향가전', '주방가전', '생활가전',
       '컴퓨터/주변기기', '카메라', '악기', '음반/음원', '계절가전', '가전행사', '명품잡화', '명품의류',
       '주방용품', '서적', '인테리어소품', '가구', '문화생활', '과일', nan, '영유아식품', '생활',
       '캠핑용품', '일용잡화', '청소/욕실용품', '문구/완구/사무용품', '음반/음원/비디오', '학습기기',
       '애완용품', '원예용품', '자동차용품', '미용용픔', '스포츠장비/용품', '유아용의류', '뷰티/헤어가전',
       '부품/액세서리', '통신가전', '자동차기기', '명품', '식품가공', '농식품행사', '의약품/의료기기',
       '유아용모자', '유제품', '문구/사무용품'], dtype=object)

In [ ]:
fd_f['중분류명_재'].isnull().sum()

69424

In [ ]:
fd_f['중분류명_재'] = fd_f['중분류명_재'].fillna('영유아')

In [ ]:
items =['위생용품', '미용용품', '생활용품', '기타행사', '축산물', '축산가공', '유제품/아이스크림', '과자류',
       '유기농', '농산물', '농산가공', '식품행사', '수산물', '수산가공', '냉동식품', '외식', '빵류/떡류',
       '가공식품_기타', '기타', '커피/차류', '음료류', '조미료', '건강식품', '주류', '액세서리/잡화',
       '모자', '패션의류/잡화_기타', '가방', '신발', '유아동의류', '영유아용품', '의류행사', '영유아의류',
       '의류', '언더웨어', '스포츠의류/신발/잡화', '골프용품', '음향가전', '주방가전', '생활가전',
       '컴퓨터/주변기기', '카메라', '악기', '음반/음원', '계절가전', '가전행사', '명품잡화', '명품의류',
       '주방용품', '서적', '인테리어소품', '가구', '문화생활', '과일', '영유아','영유아식품', '생활',
       '캠핑용품', '일용잡화', '청소/욕실용품', '문구/완구/사무용품', '음반/음원/비디오', '학습기기',
       '애완용품', '원예용품', '자동차용품', '미용용픔', '스포츠장비/용품', '유아용의류', '뷰티/헤어가전',
       '부품/액세서리', '통신가전', '자동차기기', '명품', '식품가공', '농식품행사', '의약품/의료기기',
       '유아용모자', '유제품', '문구/사무용품']

In [ ]:
len(items)

80

In [ ]:
fd_f['중분류명_재'].isnull().sum()

0

In [ ]:

from sklearn.preprocessing import LabelEncoder

encoders = LabelEncoder()
encoders.fit(items)
labelss = encoders.transform(items)

print('인코딩 변환 값:', labelss)
print('인코딩 클래스:',encoders.classes_)
print('디코딩 원본값:', encoders.inverse_transform([47, 22, 29, 10, 71, 70, 53,  8, 48, 13, 12, 36, 32, 31, 11, 45, 26,  0,  9, 74, 54,
                                             65,  4, 66, 40 ,18, 77,  2 ,37, 49, 43, 59, 44, 58, 41, 33,  6, 57, 67, 28, 75, 72, 38, 55,
                                             5,  3, 17, 16, 68,30, 61,  1, 21, 7, 42, 27, 73, 62 ,69 ,20, 56,
                                             78, 39, 46, 64, 23, 34, 51, 25, 24, 76, 63,15, 35, 14, 60, 50, 52, 19 ]))

인코딩 변환 값: [48 22 29 10 72 71 54  8 49 13 12 36 32 31 11 46 26  0  9 75 55 66  4 67
 40 18 78  2 37 50 44 60 45 59 41 33  6 58 68 28 76 73 38 56  5  3 17 16
 69 30 62  1 21  7 42 43 27 74 63 70 20 57 79 39 47 65 23 34 52 25 24 77
 64 15 35 14 61 51 53 19]
인코딩 클래스: ['가공식품_기타' '가구' '가방' '가전행사' '건강식품' '계절가전' '골프용품' '과일' '과자류' '기타' '기타행사'
 '냉동식품' '농산가공' '농산물' '농식품행사' '명품' '명품의류' '명품잡화' '모자' '문구/사무용품'
 '문구/완구/사무용품' '문화생활' '미용용품' '미용용픔' '부품/액세서리' '뷰티/헤어가전' '빵류/떡류' '생활' '생활가전'
 '생활용품' '서적' '수산가공' '수산물' '스포츠의류/신발/잡화' '스포츠장비/용품' '식품가공' '식품행사' '신발' '악기'
 '애완용품' '액세서리/잡화' '언더웨어' '영유아' '영유아식품' '영유아용품' '영유아의류' '외식' '원예용품' '위생용품'
 '유기농' '유아동의류' '유아용모자' '유아용의류' '유제품' '유제품/아이스크림' '음료류' '음반/음원' '음반/음원/비디오'
 '음향가전' '의류' '의류행사' '의약품/의료기기' '인테리어소품' '일용잡화' '자동차기기' '자동차용품' '조미료' '주류'
 '주방가전' '주방용품' '청소/욕실용품' '축산가공' '축산물' '카메라' '캠핑용품' '커피/차류' '컴퓨터/주변기기'
 '통신가전' '패션의류/잡화_기타' '학습기기']
디코딩 원본값: ['원예용품' '미용용품' '생활용품' '기타행사' '축산가공' '청소/욕실용품' '유제품' '과자류' '위생용품' '농산물'
 '농산가공' '식품행사' '수산물' '수산가공' '냉동식품' '영유아의류' '빵류/떡류' '가공식품_기타' '기타' '캠핑용품'
 '유제품/아이스크림' '자동차용품' '건강식품' '조미료' '액세서리/잡화' '모자' '통신가전' '가방' '신발' '유기농'
 '영유아식품' '의류' '영유아용품' '음향가전' '언더웨어' '스포츠의류/신발/잡화' '골프용품' '음반/음원/비디오' '주류'
 '생활가전' '커피/차류' '축산물' '악기' '음료류' '계절가전' '가전행사' '명품잡화' '명품의류' '주방가전' '서적'
 '의약품/의료기기' '가구' '문화생활' '과일' '영유아' '생활' '카메라' '인테리어소품' '주방용품' '문구/완구/사무용품'
 '음반/음원' '패션의류/잡화_기타' '애완용품' '외식' '자동차기기' '미용용픔' '스포츠장비/용품' '유아용모자'
 '뷰티/헤어가전' '부품/액세서리' '컴퓨터/주변기기' '일용잡화' '명품' '식품가공' '농식품행사' '의류행사' '유아동의류'
 '유아용의류' '문구/사무용품']

In [ ]:
import pandas as pd
df = pd.DataFrame(labelss)
df.columns=['인코딩']
# pd.get_dummies(df)

labelss =fd_f['중분류명_재'].unique()
sd = pd.DataFrame(labelss)
sd.columns=['중분류명_재']

df= pd.concat([sd,df],axis=1)
df

      중분류명_재  인코딩
0       위생용품   48
1       미용용품   22
2       생활용품   29
3       기타행사   10
4        축산물   72
..       ...  ...
75     농식품행사   14
76  의약품/의료기기   61
77     유아용모자   51
78       유제품   53
79   문구/사무용품   19

[80 rows x 2 columns]

In [ ]:
#결측치 확인하기기
print(df.isnull().sum())

중분류명_재    0
인코딩       0
dtype: int64

In [ ]:
# 기존 데이터와 (중분류 명인코딩) 한거 merge
fd_f_2=pd.merge(fd_f, df, on ='중분류명_재')
len(fd_f_2['중분류명_재'].unique())

80

In [ ]:
fd_f_2

,소분류코드,소분류명,고객번호,성별,연령대,제휴사,점포코드,구매시간,구매금액,년도,월,분기,중분류명_재,대분류명_재,시군구,인코딩
0,A010101,위생세제,1,M,60세이상,A,A12,15,9500,2014,2,1st,위생용품,일상용품,강남구,48
1,A010101,위생세제,1,M,60세이상,A,A12,15,5000,2014,9,3rd,위생용품,일상용품,강남구,48
2,A010101,위생세제,1,M,60세이상,A,A12,11,19810,2014,1,1st,위생용품,일상용품,강남구,48
3,A010101,위생세제,1,M,60세이상,A,A12,12,1000,2015,3,5th,위생용품,일상용품,강남구,48
4,A010101,위생세제,1,M,60세이상,A,A12,17,6800,2015,11,8th,위생용품,일상용품,강남구,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8336524,D060401,기타파티/팬시용품,17528,F,25세~29세,D,D8,14,8800,2015,4,6th,문구/사무용품,교육/문화용품,중랑구,19
8336525,D060401,기타파티/팬시용품,18057,F,20세~24세,D,D8,14,500,2015,3,5th,문구/사무용품,교육/문화용품,중랑구,19
8336526,D060401,기타파티/팬시용품,18977,F,20세~24세,D,D8,13,2500,2014,12,4th,문구/사무용품,교육/문화용품,중랑구,19
8336527,D060401,기타파티/팬시용품,18986,F,20세~24세,D,D8,12,9800,2015,8,7th,문구/사무용품,교육/문화용품,중랑구,19
8336528,D060401,기타파티/팬시용품,18986,F,20세~24세,D,D8,18,29400,2015,9,7th,문구/사무용품,교육/문화용품,중랑구,19

In [ ]:
# 분기별로 나누기기
d_1g = fd_f_2.query("분기 == '1st'")
d_2g = fd_f_2.query("분기 == '2nd'")
d_3g = fd_f_2.query("분기 == '3rd'")
d_4g = fd_f_2.query("분기 == '4th'")
d_5g = fd_f_2.query("분기 == '5th'")
d_6g = fd_f_2.query("분기 == '6th'")
d_7g = fd_f_2.query("분기 == '7th'")
d_8g = fd_f_2.query("분기 == '8th'")
d_1g

,소분류코드,소분류명,고객번호,성별,연령대,제휴사,점포코드,구매시간,구매금액,년도,월,분기,중분류명_재,대분류명_재,시군구,인코딩
0,A010101,위생세제,1,M,60세이상,A,A12,15,9500,2014,2,1st,위생용품,일상용품,강남구,48
2,A010101,위생세제,1,M,60세이상,A,A12,11,19810,2014,1,1st,위생용품,일상용품,강남구,48
8,A010101,위생세제,34,F,60세이상,A,A12,12,8700,2014,3,1st,위생용품,일상용품,강남구,48
9,A010101,위생세제,34,F,60세이상,A,A12,16,5000,2014,1,1st,위생용품,일상용품,강남구,48
11,A010101,위생세제,34,F,60세이상,A,A12,16,5000,2014,1,1st,위생용품,일상용품,강남구,48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8336409,D060401,기타파티/팬시용품,1359,F,55세~59세,D,D10,12,11900,2014,2,1st,문구/사무용품,교육/문화용품,노원구,19
8336457,D060401,기타파티/팬시용품,13054,F,30세~34세,D,D12,21,15000,2014,3,1st,문구/사무용품,교육/문화용품,송파구,19
8336458,D060401,기타파티/팬시용품,13315,M,45세~49세,D,D12,21,11900,2014,3,1st,문구/사무용품,교육/문화용품,송파구,19
8336469,D060401,기타파티/팬시용품,13315,M,45세~49세,D,D5,19,11900,2014,3,1st,문구/사무용품,교육/문화용품,강남구,19
8336519,D060401,기타파티/팬시용품,15444,F,25세~29세,D,D8,15,15000,2014,3,1st,문구/사무용품,교육/문화용품,중랑구,19

In [ ]:
# 점포별, 대분류명별, (대분류명 인코딩)한거 카운트 하기
d_1gi=d_1g.groupby(["점포코드",'인코딩'])[['중분류명_재']].count().reset_index()
d_2gi=d_2g.groupby(["점포코드",'인코딩'])[['중분류명_재']].count().reset_index()
d_3gi=d_3g.groupby(["점포코드",'인코딩'])[['중분류명_재']].count().reset_index()
d_4gi=d_4g.groupby(["점포코드",'인코딩'])[['중분류명_재']].count().reset_index()
d_5gi=d_5g.groupby(["점포코드",'인코딩'])[['중분류명_재']].count().reset_index()
d_6gi=d_6g.groupby(["점포코드",'인코딩'])[['중분류명_재']].count().reset_index()
d_7gi=d_7g.groupby(["점포코드",'인코딩'])[['중분류명_재']].count().reset_index()
d_8gi=d_8g.groupby(["점포코드",'인코딩'])[['중분류명_재']].count().reset_index()
d_1gi

     점포코드  인코딩  중분류명_재
0      A1    0     776
1      A1    1      41
2      A1    2      18
3      A1    4     307
4      A1    5       6
...   ...  ...     ...
4673   D8   48       6
4674   D8   55      36
4675   D8   58       1
4676   D8   61       3
4677   D8   78       1

[4678 rows x 3 columns]

In [ ]:
#인코딩 결과를 점포별로 (max) 랭킹 찾기기 
d_1gi['rank'] = d_1gi.groupby(["점포코드"])[['중분류명_재']].rank(method='max', ascending=False)
d_2gi['rank'] = d_2gi.groupby(["점포코드"])[['중분류명_재']].rank(method='max', ascending=False)
d_3gi['rank'] = d_3gi.groupby(["점포코드"])[['중분류명_재']].rank(method='max', ascending=False)
d_4gi['rank'] = d_4gi.groupby(["점포코드"])[['중분류명_재']].rank(method='max', ascending=False)
d_5gi['rank'] = d_5gi.groupby(["점포코드"])[['중분류명_재']].rank(method='max', ascending=False)
d_6gi['rank'] = d_6gi.groupby(["점포코드"])[['중분류명_재']].rank(method='max', ascending=False)
d_7gi['rank'] = d_7gi.groupby(["점포코드"])[['중분류명_재']].rank(method='max', ascending=False)
d_8gi['rank'] = d_8gi.groupby(["점포코드"])[['중분류명_재']].rank(method='max', ascending=False)

#### 중분류명 점포별 최다판매 1위 구하기

In [ ]:
# 점포별, 분기별,랭킹 1위 구하기기
d_1gi=d_1gi[d_1gi['rank']==1.0].iloc[:,:2]
d_2gi=d_2gi[d_2gi['rank']==1.0].iloc[:,:2]
d_3gi=d_3gi[d_3gi['rank']==1.0].iloc[:,:2]
d_4gi=d_4gi[d_4gi['rank']==1.0].iloc[:,:2]
d_5gi=d_5gi[d_5gi['rank']==1.0].iloc[:,:2]
d_6gi=d_6gi[d_6gi['rank']==1.0].iloc[:,:2]
d_7gi=d_7gi[d_7gi['rank']==1.0].iloc[:,:2]
d_8gi=d_8gi[d_8gi['rank']==1.0].iloc[:,:2]

In [ ]:
# 분기별로 중분류명 바꾸기기
d_1 = d_1gi.rename(columns={'인코딩':'중인코딩_1'})
d_2 = d_2gi.rename(columns={'인코딩':'중인코딩_2'})
d_3 = d_3gi.rename(columns={'인코딩':'중인코딩_3'})
d_4 = d_4gi.rename(columns={'인코딩':'중인코딩_4'})
d_5 = d_5gi.rename(columns={'인코딩':'중인코딩_5'})
d_6 = d_6gi.rename(columns={'인코딩':'중인코딩_6'})
d_7 = d_7gi.rename(columns={'인코딩':'중인코딩_7'})
d_8 = d_8gi.rename(columns={'인코딩':'중인코딩_8'})

#### <최종 점포별 분기별 중분류명>

In [ ]:
# 점포별로 분기명과 중분류명 합친거 합치기기
import pandas as pd
d_1= pd.merge(d_1, d_2, on ='점포코드',how='outer')
d_1= pd.merge(d_1, d_3, on ='점포코드',how='outer')
d_1= pd.merge(d_1, d_4, on ='점포코드',how='outer')
d_1= pd.merge(d_1, d_5, on ='점포코드',how='outer')
d_1= pd.merge(d_1, d_6, on ='점포코드',how='outer')
d_1= pd.merge(d_1, d_7, on ='점포코드',how='outer')
d_1= pd.merge(d_1, d_8, on ='점포코드',how='outer')
d_1

     점포코드  중인코딩_1  중인코딩_2  중인코딩_3  중인코딩_4  중인코딩_5  중인코딩_6  중인코딩_7  중인코딩_8
0      A1    46.0      46    46.0    46.0    46.0    46.0    46.0    46.0
1     A12    13.0      59    59.0    59.0    13.0    59.0    59.0    59.0
2      A2    46.0      46    46.0    46.0    46.0    46.0    46.0    46.0
3     A20    46.0      59    59.0    59.0    46.0    59.0    59.0    59.0
4     A24    59.0      59    59.0    59.0    46.0    59.0    46.0    46.0
..    ...     ...     ...     ...     ...     ...     ...     ...     ...
158    D8     8.0      22    22.0    22.0    22.0    22.0    22.0    22.0
159  C401     NaN       0    55.0     NaN     NaN     0.0     NaN     0.0
160  C483     NaN      13    54.0    13.0    13.0    13.0    13.0    13.0
161  C486     NaN      54    13.0    13.0    13.0    13.0    13.0    13.0
162  C513     NaN      13    13.0    13.0    13.0    54.0    13.0    13.0

[163 rows x 9 columns]

In [ ]:
d_1.isnull().sum()
d_1= d_1.fillna(method='ffill')
d_1

     점포코드  중인코딩_1  중인코딩_2  중인코딩_3  중인코딩_4  중인코딩_5  중인코딩_6  중인코딩_7  중인코딩_8
0      A1    46.0      46    46.0    46.0    46.0    46.0    46.0    46.0
1     A12    13.0      59    59.0    59.0    13.0    59.0    59.0    59.0
2      A2    46.0      46    46.0    46.0    46.0    46.0    46.0    46.0
3     A20    46.0      59    59.0    59.0    46.0    59.0    59.0    59.0
4     A24    59.0      59    59.0    59.0    46.0    59.0    46.0    46.0
..    ...     ...     ...     ...     ...     ...     ...     ...     ...
158    D8     8.0      22    22.0    22.0    22.0    22.0    22.0    22.0
159  C401     8.0       0    55.0    22.0    22.0     0.0    22.0     0.0
160  C483     8.0      13    54.0    13.0    13.0    13.0    13.0    13.0
161  C486     8.0      54    13.0    13.0    13.0    13.0    13.0    13.0
162  C513     8.0      13    13.0    13.0    13.0    54.0    13.0    13.0

[163 rows x 9 columns]

In [ ]:
d_1.to_csv("최다판매중분류(1).csv", index = False)

In [ ]:
# # 최다 중분류명을 숫자화한 인코딩 값 카운트 하기기
# d_1gi= d_1g.groupby(["점포코드",'중분류명_재'])[['인코딩']].count().reset_index()
# d_2gi= d_2g.groupby(["점포코드",'중분류명_재'])[['인코딩']].count().reset_index()
# d_3gi= d_3g.groupby(["점포코드",'중분류명_재'])[['인코딩']].count().reset_index()
# d_4gi= d_4g.groupby(["점포코드",'중분류명_재'])[['인코딩']].count().reset_index()
# d_5gi= d_5g.groupby(["점포코드",'중분류명_재'])[['인코딩']].count().reset_index()
# d_6gi= d_6g.groupby(["점포코드",'중분류명_재'])[['인코딩']].count().reset_index()
# d_7gi= d_7g.groupby(["점포코드",'중분류명_재'])[['인코딩']].count().reset_index()
# d_8gi= d_8g.groupby(["점포코드",'중분류명_재'])[['인코딩']].count().reset_index()
# d_1gi

In [ ]:
# # 인코딩값에 랭킹 매기기기
# d_1gi['rank'] = d_1gi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_2gi['rank'] = d_2gi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_3gi['rank'] = d_3gi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_4gi['rank'] = d_4gi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_5gi['rank'] = d_5gi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_6gi['rank'] = d_6gi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_7gi['rank'] = d_7gi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_8gi['rank'] = d_8gi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)

### 3.소분류명 인코딩

In [ ]:
itemst =[x for x in fd_f['소분류명'].unique()]
itemst

['위생세제',
 '뷰티상품',
 '일용잡화',
 '세트상품',
 '단기행사',
 '우육',
 '돈육',
 '계육',
 '갈비세트',
 '정육세트',
 '수입육',
 '양념육',
 '햄',
 '유제품',
 '직매입',
 '화과자',
 '햄세트',
 '친환경올가',
 '청과',
 '채소',
 '유기농채소',
 '농산가공',
 '건과',
 '선식(가루류)',
 '곡물',
 '농산단기행사',
 '청과세트',
 '건과세트',
 '곶감/송이세트',
 '수삼/더덕세트',
 '친환경세트',
 '생선',
 '건생선',
 '기타생선',
 '냉동식품',
 '굴비류',
 '멸치류',
 '안주류',
 '김류',
 '즉석구이김류',
 '건어물류',
 '건어물세트',
 '선어세트',
 '굴비세트',
 '안주세트',
 '기타건생선세트',
 '김세트',
 '멸치세트',
 '수산단기행사',
 '한식델리',
 '일식델리',
 '서양델리',
 '에스닉푸드',
 '중식델리',
 '초밥',
 '제과제빵',
 '일반가공식품',
 '특산물행사',
 '가공선물세트',
 '케익류',
 '양과자류',
 '전문베이커리',
 '떡',
 '한과',
 '한과(세트행사)',
 '양과(세트행사)',
 '반찬장류세트',
 '포숑',
 '수입단기행사',
 '기타베이커리',
 '즉석.스넥(매장)',
 '밥류',
 '면류',
 '패밀리레스토랑',
 '아이스크림',
 '커피숍',
 'KKD',
 '브랑제리',
 '브랜드샵',
 '엔젤리너스',
 '롯데리아',
 'TGIF',
 '음료',
 '대형테넌트',
 '디저트카페',
 '식당가 한식',
 '식당가 중식',
 '식당가 일식',
 '식당가 양식',
 '식당가 커피숍',
 '식당가 아이스크림',
 '생필(부대)',
 '스넥(부대)',
 '델리(부대)',
 '젓갈세트',
 '규격젓갈',
 '벌크젓갈',
 '규격김치',
 '벌크김치',
 '장류',
 '어묵',
 '가공행사',
 '즉석반찬',
 '건강식품(홍삼)',
 '건강식품',
 '건강식품(비타민)',
 '주류',
 '한차',
 '공병',
 '기타음료',
 '디저트류',
 '가공2단기행사',
 '원두커피',
 '수입식품',
 '스테이셔너리',
 '넥타이(특정)',
 '스카프(특정)',
 '양말(특정)',
 '손수건(특정)',
 '스타킹(특정)',
 '모자(특정)',
 '우/양산(특정)',
 '장갑(특정)',
 '기타',
 '누셀렉트샵',
 '모자(단기행사)',
 '패션갤러리움',
 '무인양품',
 '영플라자(패션내의)',
 '영플라자(영트랜디)',
 '영플라자(기타)',
 '선글라스(특정)',
 '영플라자(패션)',
 '아이웨어',
 '헤어',
 '수입ACC',
 '헤어ACC',
 '국산ACC',
 '14K',
 '넥타이핀',
 '기타(가발포장담배연구사진수선)',
 '영플라자(장신)',
 'ACC Bloom (1F)',
 'ACC Bloom (3F)',
 '화장품',
 '기초 화장품',
 '색조 화장품',
 '향수',
 '기초A',
 '영플라자(화장품)',
 '영플라자 색조',
 '아울렛(화장품)',
 '남성 화장품',
 '조화',
 '보석',
 '시계',
 '네셔널',
 '가방',
 '임대',
 '4대 B/D',
 'Bag&Bag',
 '영플라자(구두)',
 '캐릭터 여화',
 '구두시즌',
 '캐릭터 남화',
 '구두단기행사',
 'NB 여화',
 'shoe`n shoe',
 '금강그룹',
 '정상구두',
 '캐주얼화',
 'N/B 아동복',
 'L/C 아동복',
 '수입 아동복',
 '고정행사(아동복)',
 '아동잡화',
 '아동신발',
 '단기행사(아동복)',
 '키즈',
 '유아복',
 '유아용품',
 '내의',
 '완구',
 '토들러',
 '아동놀이시설',
 '영플라자(영캐주얼)',
 '영플라자(진/유니)',
 '영플라자(이지)',
 '영플라자(스트리트)',
 '올리브핫스텁',
 '영플라자(영캐릭터)',
 '영플라자(영밸류)',
 '영밸류 캐주얼',
 '영플라자(쿨캐주얼)',
 '영플라자 컬처캐주얼',
 '수입브릿지',
 '수입캐주얼',
 '캐릭터캐주얼',
 '수입캐릭터',
 '이지캐주얼(행사)',
 '스트리트',
 'UNIT',
 '영캐주얼',
 '영캐주얼행사',
 '영 캐릭터',
 '영 트렌디',
 'global SPA',
 '영 컨템포러리',
 '진캐주얼',
 '이지캐주얼',
 '유니섹스캐주얼행사',
 '쿨캐주얼',
 '프리미엄진',
 '컬처캐주얼',
 'GR-8',
 'SPACE 5.1',
 '편집샵',
 '진스퀘어',
 '캐주얼피혁',
 '캐주얼단품',
 '비아스텔리나',
 '라뉴',
 '비트윈',
 'global 편집샵',
 'KHOS',
 '영플라자(KHOS)',
 '유니크샵',
 '영플라자(영스트리트)',
 '영스트리트',
 '영플라자(영캐주얼행사)',
 '케이웨이 상품군',
 '까르뜨블랑슈 상품군',
 '펜필드 상품군',
 '팀버랜드 상품군',
 'Knit & Knot(캐슬플라자)',
 '커리어',
 '세이브더칠드런',
 '밸류커리어',
 '안토니모라토 상품군',
 '크로커다일 상품군',
 '트래디셔널',
 'Knit & Knot',
 '엘레강스',
 '시니어',
 '나파피리상품군',
 '란제리',
 '패션내의',
 '란제리행사',
 'EC(해외잡화)',
 '더블라우스',
 '유니폼',
 '홈웨어',
 '니트단품',
 '디자이너',
 '디자이너부틱',
 '모피',
 '피혁',
 '숙녀고정행사',
 '숙녀단기행사',
 'N.B정장',
 '직수입정장',
 '보기밀라노',
 '정장점행사',
 '갤럭시',
 '로가디스',
 '마에스트로',
 '캠브리지',
 '바쏘',
 '빨질레리',
 '니나리찌',
 '닥스',
 '킨록앤더슨',
 '다반',
 '브룩스브라더스',
 '아울렛엘지패션',
 '시티캐주얼',
 '시티정장바지',
 '시티단기행사',
 'Maniz',
 '갤럭시라이프스타일',
 '로가디스그린',
 '일꼬르소',
 '클럽캠브리지',
 '프랑코페라로',
 '인디안',
 '아날도바시니',
 '에디션',
 '벨라모',
 'el Trail',
 'OUTDOOR+1',
 'Fitness Square',
 '청백',
 '다비드컬렉션',
 '남성잡화ACC2',
 'ARCHIV',
 'MODIUM',
 'Last Scene',
 '건강수면샵',
 '수입화',
 '어반스타일',
 '트래디셔널Ⅱ',
 'el Travel',
 '빈폴상품군',
 '폴로상품군',
 '라코스테상품군',
 '타미힐피거상품군',
 '헤지스상품군',
 '헨리코튼상품군',
 '올젠상품군',
 '프레드페리상품군',
 '교복',
 '비지니스군',
 '셔츠고정행사',
 '셔츠단기행사',
 '남성잡화 ACC',
 '트랜디',
 '컨템포러리',
 '어반캐주얼',
 '지이크',
 'ANDZ',
 '레노마',
 '코모도스퀘어',
 '지오송지오',
 'TNGT',
 '리버클래시',
 '바버 상품군',
 '아웃도아',
 '수영복',
 '가 방',
 '운동용품',
 '스포츠용품',
 '스키',
 '고정행사(레져)',
 '단기행사(레져)',
 '선글라스',
 '등산화',
 'L/C 아웃도어',
 '직수입 아웃도어',
 '노스페이스',
 '에이글',
 '코오롱스포츠',
 'K2',
 '아이더',
 '블랙야크',
 '마모트',
 '컬럼비아',
 '네파',
 '이젠벅',
 '밀레',
 '라푸마',
 '슈나이더',
 '머렐',
 '빈폴아웃도어',
 '디스커버리',
 '몽벨',
 '센터폴',
 '트렉스타(의)',
 '트렉스타(신)',
 '카리모어',
 '레드페이스',
 '에코로바',
 '웨스트우드',
 '투스카로라',
 '아크테릭스',
 '몬츄라',
 '피엘라벤',
 '파타고니아',
 '오클리',
 '볼레',
 '마모트카페(Rodge201)',
 '프레지던츠골프',
 '스포츠의류',
 '스포츠화',
 '고정행사(스포츠)',
 '단기행사(스포츠)',
 '나이키의류',
 '아디다스의류',
 '나이키화',
 '아디다스화',
 '뉴발란스아울렛',
 '배드민턴스퀘어',
 '아울렛 제일모직',
 'N/B골프의류',
 'L/C골프의류',
 '직수입 골프의류',
 '골프용품',
 '단기행사(골프)',
 '아놀드파마',
 '닥스골프',
 '헤지스골프',
 '잭니클라우스',
 '엘로드',
 '울시',
 '레노마골프',
 '휠라골프',
 '핑',
 '팬텀골프',
 '슈페리어',
 '이동수골프',
 '빈폴골프',
 '캘러웨이',
 '타이틀리스트',
 '김영주골프',
 'JDX골프',
 '피가로',
 '링스',
 '까스텔바작',
 '엠유스포츠',
 '보그너',
 '아다바트',
 '먼싱웨어',
 '르꼬끄골프',
 '파리게이츠',
 '블랙앤화이트',
 '나이키골프',
 '아디다스골프',
 '휴고보스골프',
 '데상트골프',
 '매일통상',
 '매직스포츠',
 '골프존마켓',
 '애플라인드',
 '파리게이츠 상품군',
 '해리토리 상품군',
 '국산A/V',
 '국산냉장고.세탁기',
 '수입냉장고',
 '수입세탁기',
 '수입A/V',
 '가스기기',
 '수입청소기 외',
 '기능성소품',
 'MP3 外',
 '컴퓨터',
 'IT 게임기S/W',
 '디지털카메라',
 '피아노/악기',
 '음반',
 '명품오디오',
 '에어컨',
 '전기밥솥',
 '수입소형가전',
 '기타국산소형가전',
 '김치냉장고',
 '건강가전',
 '행사',
 '에스프레소',
 '갤러리',
 '수입잡화',
 '수입의류',
 '직수입',
 '잡화멀티샵',
 '명품잡화',
 '명품잡화보석',
 '명품기타',
 '명품잡화행사',
 '어덜트',
 '명품남성',
 '명품의류행사',
 '명품의류기타',
 '명품시계기타',
 '명품보석',
 '힐앤토트',
 '엘리든',
 '남성해외패션',
 '수입주방',
 '주방잡화',
 '수      저',
 '국산주방',
 '주방단기행사',
 '임      대',
 '휴모니아',
 '토탈리빙',
 '서적',
 '이미용',
 '캔들디퓨져',
 '타월',
 '욕실용품',
 '매트',
 '장식소품',
 '토탈데코',
 '그림',
 '소품가구',
 '기능성침대',
 '크리스탈',
 '그라스',
 '국산도자기',
 '수입도자기',
 '전통도자기',
 '식기단기행사',
 '락앤락',
 '종합가구',
 '수입가구',
 '침대',
 '소파',
 '식탁',
 '원목학생철재',
 '일반침대',
 '건강침대',
 '일반침대(에이스)',
 '건강침대(흙침대)',
 '카페트',
 'N.B',
 'L.B',
 '수입침구',
 '한실침구',
 '수예소품',
 '수예단기행사',
 '건강베개',
 '아동침구',
 '웨딩',
 '가지',
 '고추',
 '구색 호박',
 '기타열매채소',
 '단호박',
 '애호박',
 '여주',
 '오이',
 '옥수수',
 '친환경열매채소',
 '콩류',
 '피망',
 '건버섯',
 '느타리버섯',
 '버섯모둠',
 '버섯선물세트',
 '새송이버섯',
 '양송이버섯',
 '이색버섯',
 '팽이버섯',
 '표고버섯',
 '나물/부침',
 '반찬류',
 '젓갈류',
 '즉석김치류',
 '즉석국탕/볶음',
 '제철반찬',
 '김장김치',
 '저염젓갈',
 '일반젓갈',
 '절임반찬',
 '조림반찬',
 '메인요리',
 '볶음/무침반찬',
 '일반미',
 '기능성미',
 '친환경양곡',
 '미곡류',
 '보리류',
 '잡곡기타',
 '혼합잡곡',
 '친환경잡곡',
 '벌크잡곡',
 '즉석도정미',
 '친환경도정미',
 '양곡가공',
 '시금치',
 '상추',
 '미나리',
 '부추',
 '쑥갓',
 '깻잎',
 '얼갈이',
 '아욱',
 '근대',
 '양배추',
 '기타잎채소',
 '쌈채소',
 '봄동',
 '죽순',
 '고구마순',
 '생나물',
 '친환경채소(특약)',
 '친환경잎채소',
 '감자',
 '고구마',
 '당근',
 '연근',
 '우엉',
 '마',
 '기타뿌리채소',
 '기타과채류',
 '기타호박',
 '다다기오이',
 '취청오이',
 '가시오이',
 '기타오이',
 '친환경팽이버섯',
 '일반느타리버섯',
 '기타버섯',
 '친환경참맛느타리',
 '버섯류 선물세트',
 '파프리카',
 '양상추',
 '브로콜리',
 '구색양채',
 '즙용양채',
 '아스파라거스',
 '샐러드채소',
 '구색샐러드채소',
 '즙용샐러드채소',
 '친환경샐러드채소',
 '인삼',
 '기타약초',
 '더덕',
 '황기',
 '대파',
 '양파',
 '깐마늘',
 '생강',
 '건고추',
 '기타양념',
 '쪽파',
 '피마늘',
 '마늘쫑',
 '양념류 선물세트',
 '친환경쌈채소',
 '친환경뿌리채소',
 '친환경양념채소',
 '친환경김치채소',
 '배추',
 '열무',
 '무우',
 '갓',
 '알타리무',
 'Local근대',
 'Local기타잎채소',
 'Local깻잎',
 'Local부추',
 'Local상추',
 'Local시금치',
 'Local쌈채소',
 'Local쑥갓',
 'Local아욱',
 'Local갓',
 'Local얼갈이',
 'Local열무',
 '간편구색',
 '간편양념',
 '드레싱',
 '샐러드',
 '대구',
 '우럭',
 '도미',
 '조기',
 '고등어',
 '갈치',
 '꽁치',
 '명태',
 '가자미',
 '삼치',
 '임연수',
 '아귀',
 '병어',
 '게',
 '구색선어',
 '오징어류',
 '민어',
 '연어',
 '굴비',
 '반건생선',
 '냉동포장',
 '국산고등어',
 '국산고등어자반',
 '국산삼치',
 '국산대구',
 '국산도미',
 '국산민어',
 '국산청어',
 '국산금태',
 '국산우럭',
 '국산임연수어',
 '국산아귀',
 '국산병어',
 '국산기타구색생선',
 '국산꽁치',
 '국산가자미',
 '국산오징어',
 '국산한치',
 '국산참조기',
 '부세조기',
 '국산백조기',
 '긴가이석태',
 '기타조기',
 '국산명태',
 '국산꽃게',
 '국산대게',
 '국산홍게',
 '국산갈치',
 '마른안주 선물세트',
 '해조류세트',
 '멸치황태세트',
 '즉석어포',
 '즉석오징어',
 '건오징어',
 '조미오징어',
 '육포',
 '쥐치포',
 '멸치',
 '황태북어',
 '김',
 '조미김',
 '미역',
 '다시마',
 '즉석안주',
 '즉석김',
 '동해안건오징어',
 '반건오징어',
 '울릉도건오징어',
 '원양산건오징어',
 '백진미',
 '홍진미',
 '훈제구이진미',
 '국산육포',
 '돈닭치즈육포',
 '수입산육포',
 '구운쥐치포',
 '어포류',
 '육포세트',
 'F/F기타',
 '사진관',
 '안경점',
 '유원시설',
 '소극장',
 '뷔페레스토랑',
 '한식레스토랑',
 '중식레스토랑',
 '일식레스토랑',
 '기타레스토랑',
 '커피',
 '생과일',
 '기프트 샵',
 '경정비',
 '회전초밥',
 '푸드몰',
 '케익',
 '식빵',
 '과자빵',
 '페스츄리류',
 '도넛류',
 '온라인 베이커리',
 '꼬치',
 '훈제/로스트',
 '일반튀김',
 '치킨',
 '도시락',
 '김밥',
 '족발',
 '순대',
 '구이',
 '포장반찬',
 '김치',
 '젓갈',
 '반찬',
 '선식',
 '지역특산물',
 '떡/강정',
 '먹거리',
 '전통간식',
 '월드간식',
 '한식',
 '아시안',
 '양식',
 '후라이드',
 '즉석어묵',
 '피자',
 '베이크',
 '과일음료',
 '과채음료',
 '냉장차음료',
 '냉장커피음료',
 '수입냉장음료',
 '냉장음료',
 '데일리처분',
 '기능성우유',
 '친환경우유',
 '어린이우유',
 '멸균흰우유',
 '일반흰우유',
 '기능성시유',
 '테트라시유',
 '과일맛우유',
 '커피/초코우유',
 '견과우유/냉장두유',
 '멸균가공우유',
 '일반가공유',
 '펫가공유',
 '테트라가공유',
 '마시는요구르트',
 '어린이/액상요구르트',
 '드링크요구르트',
 '떠먹는요구르트',
 '치즈',
 '버터/마가린',
 '디저트',
 '크림/연유',
 '일반빵류',
 '식빵류',
 '찐빵류',
 '패스트리',
 '간식용치즈',
 '슬라이스치즈',
 '요리용치즈',
 '냉장케익',
 '젤리',
 '푸딩',
 '크림연유',
 '자연조미료',
 '가공조미료',
 '식초',
 '소금',
 '향신료',
 '설탕',
 '액젓',
 '천연조미료',
 '케찹',
 '마요네즈',
 '소스',
 '음용식초',
 '물엿/올리고당',
 '간장',
 '고추장',
 '된장',
 '쌈장',
 '춘장',
 '식용유',
 '참기름',
 '기타고급유',
 '올리브유',
 '일반유',
 '카놀라유',
 '포도씨유',
 '마가린',
 '조미혼합세트',
 '식용유세트',
 '참기름세트',
 '식용유지세트',
 '기타세트',
 '곡물가루',
 '농산가루',
 '가공선식',
 '부침/튀김가루',
 '홈메이드믹스',
 '제빵재료',
 '직영식자재',
 '자연향신료',
 '요리식초',
 '음료식초',
 '액상과당',
 '수입소스',
 '수입유지',
 '수입장류',
 '수입조미료',
 '분말조리식품',
 '즉석밥/죽',
 '봉지면',
 '용기면',
 '국수',
 '당면',
 '건냉면',
 '생면',
 '파스타류',
 '유아푸드',
 '분유',
 '이유식',
 '일반잼',
 '과일잼',
 '스프레드',
 '프리미엄잼',
 '농산물통조림',
 '수산통조림',
 '축산물통조림',
 '과일통조림',
 '참치통조림',
 '채소통조림',
 '통조림선물세트',
 '혼합선물세트',
 '유아과자',
 '유아기타간식',
 '유아음료',
 '성인두유',
 '유아두유',
 '커피크림',
 '인스턴트커피',
 '커피선물세트',
 '코코아',
 '녹차',
 '액상차',
 '티백차',
 '식수용차',
 'T-SHOP',
 '침출차',
 '분말차',
 '아이스티',
 '건강미용차',
 '차 선물세트',
 '꿀',
 '홍삼',
 '비타민',
 '꿀 선물세트',
 '건강선물세트',
 '국산담배',
 '수입담배',
 '믹스커피',
 '아이스커피',
 '용기리필커피',
 '분쇄원두커피',
 '스틱원두커피',
 '캡슐원두커피',
 '티백/드립 커피',
 '홀빈원두커피',
 '차선물세트',
 '국산꿀',
 '수입꿀',
 '감자스낵',
 '콘스낵',
 '일반스낵',
 '쌀스낵',
 '기타스낵',
 '온라인 스낵',
 '쿠키',
 '크래커',
 '샌드',
 '웨하스',
 '스틱과자',
 '온라인 비스켓',
 '파이',
 '케이크',
 '온라인 파이',
 '패밀리용시리얼',
 '어린이용시리얼',
 '성인용시리얼',
 '온라인 시리얼',
 '하드캔디',
 '소프트캔디',
 '토이캔디',
 '워터젤리',
 '팥빙수재료',
 '온라인 캔디',
 '국산초콜릿',
 '초콜릿바',
 '판초콜릿',
 '쉘초콜릿',
 '바초콜릿',
 '코팅초콜릿',
 '가공초콜릿',
 '온라인 초콜릿',
 '일반껌',
 '기호껌',
 '기능성껌',
 '풍선껌',
 '농산안주',
 '스넥안주',
 '기타안주',
 '기호한과',
 '과자선물세트',
 '유기농과자',
 '프리미엄비스켓',
 '프리미엄스낵',
 '프리미엄초콜릿',
 '프리미엄캔디',
 '프리미엄파이',
 '간식용소시지',
 '기타 간식용과자',
 '맛밤류',
 '수입껌',
 '수입비스켓',
 '수입스낵',
 '수입초콜릿',
 '수입캔디',
 '수입파이',
 '온라인수입과자',
 '캐릭터과자',
 '옛날과자',
 '온라인전통과자',
 '생수',
 '국내생수',
 '수입생수',
 '탄산수',
 '채소음료',
 '과채혼합음료',
 '어린이음료',
 '유기농음료',
 '온라인과채음료',
 '과일/야채음료',
 '선물세트 과즙음료',
 '두유',
 '영유아두유',
 '사이다',
 '콜라',
 '혼합탄산',
 '이온음료',
 '커피음료',
 '차음료',
 '혼합음료',
 '차혼합음료',
 '의약외품음료',
 '기능성건강음료',
 '비타민음료',
 ...]

In [ ]:
len(itemst)

3225

In [ ]:
from sklearn.preprocessing import LabelEncoder

encodert = LabelEncoder()
encodert.fit(itemst)
labelst = encodert.transform(itemst)

print('인코딩 변환 값:',labelst)
print('인코딩 클래스:',encodert.classes_)

인코딩 변환 값: [2137 1272 2319 ... 1790 1791  961]
인코딩 클래스: ['14K' '2단우산' '3단우산' ... '히터' '히터기' '힐앤토트']

In [ ]:
import pandas as pd

df = pd.DataFrame(labelst)
df.columns=['인코딩']
# pd.get_dummies(df)

labelst =fd_f['소분류명'].unique()
sd = pd.DataFrame(labelst)
sd.columns=['소분류명']

df= pd.concat([sd,df],axis=1)
df

               소분류명   인코딩
0              위생세제  2137
1              뷰티상품  1272
2              일용잡화  2319
3              세트상품  1458
4              단기행사   756
...             ...   ...
3220  블러셔/쉐이딩/하이라이터  1297
3221          아이라이너  1789
3222          아이브로우  1790
3223          아이섀도우  1791
3224         메이크업세트   961

[3225 rows x 2 columns]

In [ ]:
# 결측치 확인 -> 없음
df.isnull().sum()

소분류명    0
인코딩     0
dtype: int64

In [ ]:
# 기존 데이터와 (소분류명 인코딩)한거 merge 함.
fd_f_3 = pd.merge(fd_f, df, on ='소분류명')
fd_f_3

,소분류코드,소분류명,고객번호,성별,연령대,제휴사,점포코드,구매시간,구매금액,년도,월,분기,중분류명_재,대분류명_재,시군구,인코딩
0,A010101,위생세제,1,M,60세이상,A,A12,15,9500,2014,2,1st,위생용품,일상용품,강남구,2137
1,A010101,위생세제,1,M,60세이상,A,A12,15,5000,2014,9,3rd,위생용품,일상용품,강남구,2137
2,A010101,위생세제,1,M,60세이상,A,A12,11,19810,2014,1,1st,위생용품,일상용품,강남구,2137
3,A010101,위생세제,1,M,60세이상,A,A12,12,1000,2015,3,5th,위생용품,일상용품,강남구,2137
4,A010101,위생세제,1,M,60세이상,A,A12,17,6800,2015,11,8th,위생용품,일상용품,강남구,2137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8336524,D080205,메이크업세트,8915,F,35세~39세,D,D8,14,19900,2014,9,3rd,미용용품,일상용품,중랑구,961
8336525,D080205,메이크업세트,8915,F,35세~39세,D,D8,11,9800,2015,11,8th,미용용품,일상용품,중랑구,961
8336526,D080205,메이크업세트,10901,F,45세~49세,D,D8,15,28000,2015,1,5th,미용용품,일상용품,중랑구,961
8336527,D080205,메이크업세트,16424,M,25세~29세,D,D8,18,1200,2015,6,6th,미용용품,일상용품,중랑구,961
8336528,D080205,메이크업세트,17528,F,25세~29세,D,D8,19,14400,2015,3,5th,미용용품,일상용품,중랑구,961

In [ ]:
d_1f = fd_f_3.query("분기 == '1st'")
d_2f = fd_f_3.query("분기 == '2nd'")
d_3f = fd_f_3.query("분기 == '3rd'")
d_4f = fd_f_3.query("분기 == '4th'")
d_5f = fd_f_3.query("분기 == '5th'")
d_6f = fd_f_3.query("분기 == '6th'")
d_7f = fd_f_3.query("분기 == '7th'")
d_8f = fd_f_3.query("분기 == '8th'")
# d_1f

In [ ]:
d_1fi= d_1f.groupby(["점포코드",'인코딩'])[['소분류명']].count().reset_index()
d_2fi= d_2f.groupby(["점포코드",'인코딩'])[['소분류명']].count().reset_index()
d_3fi= d_3f.groupby(["점포코드",'인코딩'])[['소분류명']].count().reset_index()
d_4fi= d_4f.groupby(["점포코드",'인코딩'])[['소분류명']].count().reset_index()
d_5fi= d_5f.groupby(["점포코드",'인코딩'])[['소분류명']].count().reset_index()
d_6fi= d_6f.groupby(["점포코드",'인코딩'])[['소분류명']].count().reset_index()
d_7fi= d_7f.groupby(["점포코드",'인코딩'])[['소분류명']].count().reset_index()
d_8fi= d_8f.groupby(["점포코드",'인코딩'])[['소분류명']].count().reset_index()
# d_1fi

In [ ]:
d_1fi['rank'] = d_1fi.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_2fi['rank'] = d_2fi.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_3fi['rank'] = d_3fi.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_4fi['rank'] = d_4fi.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_5fi['rank'] = d_5fi.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_6fi['rank'] = d_6fi.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_7fi['rank'] = d_7fi.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_8fi['rank'] = d_8fi.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
# d_1fi

#### 소분류명 점포별 최다판매 1위 구하기

In [ ]:
d_1fi=d_1fi[d_1fi['rank']==1.0].iloc[:,:2]
d_2fi=d_2fi[d_2fi['rank']==1.0].iloc[:,:2]
d_3fi=d_3fi[d_3fi['rank']==1.0].iloc[:,:2]
d_4fi=d_4fi[d_4fi['rank']==1.0].iloc[:,:2]
d_5fi=d_5fi[d_5fi['rank']==1.0].iloc[:,:2]
d_6fi=d_6fi[d_6fi['rank']==1.0].iloc[:,:2]
d_7fi=d_7fi[d_7fi['rank']==1.0].iloc[:,:2]
d_8fi=d_8fi[d_8fi['rank']==1.0].iloc[:,:2]

In [ ]:
d_1i = d_1fi.rename(columns={'인코딩':'소인코딩_1'})
d_2i = d_2fi.rename(columns={'인코딩':'소인코딩_2'})
d_3i = d_3fi.rename(columns={'인코딩':'소인코딩_3'})
d_4i = d_4fi.rename(columns={'인코딩':'소인코딩_4'})
d_5i = d_5fi.rename(columns={'인코딩':'소인코딩_5'})
d_6i = d_6fi.rename(columns={'인코딩':'소인코딩_6'})
d_7i = d_7fi.rename(columns={'인코딩':'소인코딩_7'})
d_8i = d_8fi.rename(columns={'인코딩':'소인코딩_8'})

In [ ]:
import pandas as pd
m_1= pd.merge(d_1i, d_2i, on ='점포코드',how='outer')
m_1= pd.merge(m_1, d_3i, on ='점포코드',how='outer')
m_1= pd.merge(m_1, d_4i, on ='점포코드',how='outer')
m_1= pd.merge(m_1, d_5i, on ='점포코드',how='outer')
m_1= pd.merge(m_1, d_6i, on ='점포코드',how='outer')
m_1= pd.merge(m_1, d_7i, on ='점포코드',how='outer')
m_1= pd.merge(m_1, d_8i, on ='점포코드',how='outer')
m_1

     점포코드  소인코딩_1  소인코딩_2  소인코딩_3  소인코딩_4  소인코딩_5  소인코딩_6  소인코딩_7  소인코딩_8
0      A1  2606.0  2606.0  2606.0  2606.0  2606.0  2606.0  2606.0  2606.0
1     A12  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0
2      A2  1603.0  2606.0  2142.0  2142.0  2142.0  2606.0  2142.0  2142.0
3     A20  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0
4     A24  2606.0  2606.0  2250.0  2250.0  2200.0  2606.0  2200.0  2250.0
..    ...     ...     ...     ...     ...     ...     ...     ...     ...
158  C482     NaN  2285.0  2285.0   246.0  2285.0     NaN  1393.0     NaN
159  C500     NaN   246.0   246.0     NaN     NaN   246.0     NaN  2285.0
160  C540     NaN  1110.0  2756.0     NaN  1393.0  1393.0  2791.0  2791.0
161   D10     NaN  2288.0  2936.0  2799.0  2756.0  2832.0  2304.0  2304.0
162  C356     NaN     NaN   830.0  2455.0  2455.0  2455.0  2455.0   338.0

[163 rows x 9 columns]

#### <최종 점포별 분기별 소분류명>

In [ ]:
m_1.isnull().sum()
m_1= m_1.fillna(method='ffill')
m_1

     점포코드  소인코딩_1  소인코딩_2  소인코딩_3  소인코딩_4  소인코딩_5  소인코딩_6  소인코딩_7  소인코딩_8
0      A1  2606.0  2606.0  2606.0  2606.0  2606.0  2606.0  2606.0  2606.0
1     A12  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0
2      A2  1603.0  2606.0  2142.0  2142.0  2142.0  2606.0  2142.0  2142.0
3     A20  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0  2200.0
4     A24  2606.0  2606.0  2250.0  2250.0  2200.0  2606.0  2200.0  2250.0
..    ...     ...     ...     ...     ...     ...     ...     ...     ...
158  C482  2799.0  2285.0  2285.0   246.0  2285.0  1126.0  1393.0  1386.0
159  C500  2799.0   246.0   246.0   246.0  2285.0   246.0  1393.0  2285.0
160  C540  2799.0  1110.0  2756.0   246.0  1393.0  1393.0  2791.0  2791.0
161   D10  2799.0  2288.0  2936.0  2799.0  2756.0  2832.0  2304.0  2304.0
162  C356  2799.0  2288.0   830.0  2455.0  2455.0  2455.0  2455.0   338.0

[163 rows x 9 columns]

In [ ]:
m_1.to_csv("최다판매소분류(1).csv", index = False)

In [ ]:
# d_1fi= d_1f.groupby(["점포코드",'소분류명'])[['인코딩']].count().reset_index()
# d_2fi= d_2f.groupby(["점포코드",'소분류명'])[['인코딩']].count().reset_index()
# d_3fi= d_3f.groupby(["점포코드",'소분류명'])[['인코딩']].count().reset_index()
# d_4fi= d_4f.groupby(["점포코드",'소분류명'])[['인코딩']].count().reset_index()
# d_5fi= d_5f.groupby(["점포코드",'소분류명'])[['인코딩']].count().reset_index()
# d_6fi= d_6f.groupby(["점포코드",'소분류명'])[['인코딩']].count().reset_index()
# d_7fi= d_7f.groupby(["점포코드",'소분류명'])[['인코딩']].count().reset_index()
# d_8fi= d_8f.groupby(["점포코드",'소분류명'])[['인코딩']].count().reset_index()
# # d_1fi

In [ ]:
# d_1fi['rank'] = d_1fi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_2fi['rank'] = d_2fi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_3fi['rank'] = d_3fi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_4fi['rank'] = d_4fi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_5fi['rank'] = d_5fi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_6fi['rank'] = d_6fi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_7fi['rank'] = d_7fi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# d_8fi['rank'] = d_8fi.groupby(["점포코드"])[['인코딩']].rank(method='max', ascending=False)
# # d_1fi

### 1.1 최다 판매 시간

In [ ]:
#기존 import
import pandas as pd

compet_1  = pd.read_csv("/content/drive/MyDrive/과제3/경쟁사이용 - 복사본.txt", sep = ",", encoding = "cp949")
demo_1    = pd.read_csv("/content/drive/MyDrive/과제3/CUSTDEMO.txt", sep = ",", encoding = "cp949")
prodpur_1 = pd.read_csv("/content/drive/MyDrive/과제3/구매상품TR - 복사본.txt", sep = ",", encoding = "cp949")
member_1  = pd.read_csv("/content/drive/MyDrive/과제3/멤버십여부 - 복사본.txt", sep = ",", encoding = "cp949")
prodcl_1  = pd.read_csv("/content/drive/MyDrive/과제3/상품분류 - 복사본.txt", sep = ",", encoding = "cp949")
channel_1 = pd.read_csv("/content/drive/MyDrive/과제3/채널이용 - 복사본.txt", sep = ",", encoding = "cp949")

final_t= pd.read_csv("/content/drive/MyDrive/과제3/upperclass_final.txt", sep = ",")
final_t= final_t[['소분류코드',"소분류명"]]

final_list= pd.read_csv("/content/drive/MyDrive/과제3/final_store_list.csv", sep = ",")
final_list = final_list.iloc[:,1:]

final_df = pd.read_csv("/content/drive/MyDrive/과제3/final_df_purchase.csv", sep = ",")
final_df = final_df.iloc[:,1:]

f_list = pd.read_excel("/content/drive/MyDrive/과제3/상품분류_재.xlsx")
f_list = f_list[["소분류코드",'중분류명_재','대분류명_재']]

#칼럼분류 
final_df = final_df[["제휴사",'소분류코드','고객번호','점포코드','구매시간','구매금액','년도','월','분기']]

#타입바꾸기
final_df["고객번호"] = final_df["고객번호"].astype("str")

# demo 데이터 전처리
demo_1["고객번호"] = demo_1["고객번호"].astype("str")
demo_1= demo_1[["고객번호","성별","연령대"]]

# demo 데이터 전처리
demo_1["고객번호"] = demo_1["고객번호"].astype("str")
demo_1= demo_1[["고객번호","성별","연령대"]]

<ipython-input-39-83ce88560b86>:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  demo_1["고객번호"] = demo_1["고객번호"].astype("str")

In [ ]:
#기존 pd.merge
import pandas as pd
d_f = pd.DataFrame()
d_f = pd.merge(demo_1, final_df, on ='고객번호')
d_flist = pd.merge(d_f, f_list, on ='소분류코드')
d_list = pd.merge(d_flist, final_list, on ='점포코드')
fd_f = pd.merge(final_t, d_list, on ='소분류코드')
fd_f

,소분류코드,소분류명,고객번호,성별,연령대,제휴사,점포코드,구매시간,구매금액,년도,월,분기,중분류명_재,대분류명_재,시군구
0,A010101,위생세제,1,M,60세이상,A,A12,15,9500,2014,2,1st,위생용품,일상용품,강남구
1,A010101,위생세제,1,M,60세이상,A,A12,15,5000,2014,9,3rd,위생용품,일상용품,강남구
2,A010101,위생세제,1,M,60세이상,A,A12,11,19810,2014,1,1st,위생용품,일상용품,강남구
3,A010101,위생세제,1,M,60세이상,A,A12,12,1000,2015,3,5th,위생용품,일상용품,강남구
4,A010101,위생세제,1,M,60세이상,A,A12,17,6800,2015,11,8th,위생용품,일상용품,강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8336524,D080401,일반네일/케어류,16424,M,25세~29세,D,D8,19,8000,2015,8,7th,미용용품,일상용품,중랑구
8336525,D080401,일반네일/케어류,18977,F,20세~24세,D,D8,19,55000,2014,8,3rd,미용용품,일상용품,중랑구
8336526,D080401,일반네일/케어류,18977,F,20세~24세,D,D8,12,3700,2015,6,6th,미용용품,일상용품,중랑구
8336527,D080401,일반네일/케어류,18977,F,20세~24세,D,D8,12,12000,2015,6,6th,미용용품,일상용품,중랑구
8336528,D080401,일반네일/케어류,18986,F,20세~24세,D,D8,14,13500,2015,9,7th,미용용품,일상용품,중랑구

In [ ]:
#타입바꾸기
fd_f["구매시간"] = fd_f["구매시간"].astype("str")

In [ ]:
# 분기 나누기
d_1 = fd_f.query("분기 == '1st'")
d_2 = fd_f.query("분기 == '2nd'")
d_3 = fd_f.query("분기 == '3rd'")
d_4 = fd_f.query("분기 == '4th'")
d_5 = fd_f.query("분기 == '5th'")
d_6 = fd_f.query("분기 == '6th'")
d_7 = fd_f.query("분기 == '7th'")
d_8 = fd_f.query("분기 == '8th'")

In [ ]:
# 점포별 구매시간별 그룹바이 하고, 소분류명으로 카운트 하기
d_1i=d_1.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_2i=d_2.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_3i=d_3.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_4i=d_4.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_5i=d_5.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_6i=d_6.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_7i=d_7.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_8i=d_8.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_1i

     점포코드 구매시간  소분류명
0      A1    1     1
1      A1   10   613
2      A1   11  2155
3      A1   12  3491
4      A1   13  3925
...   ...  ...   ...
2380   D8   19    15
2381   D8   20    15
2382   D8   21     8
2383   D8   22     7
2384   D8    9     1

[2385 rows x 3 columns]

In [ ]:
d_1i['rank'] = d_1i.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_2i['rank'] = d_2i.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_3i['rank'] = d_3i.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_4i['rank'] = d_4i.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_5i['rank'] = d_5i.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_6i['rank'] = d_6i.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_7i['rank'] = d_7i.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)
d_8i['rank'] = d_8i.groupby(["점포코드"])[['소분류명']].rank(method='max', ascending=False)

In [ ]:
d_1i=d_1i[d_1i['rank']==1.0].iloc[:,:2]
d_2i=d_2i[d_2i['rank']==1.0].iloc[:,:2]
d_3i=d_3i[d_3i['rank']==1.0].iloc[:,:2]
d_4i=d_4i[d_4i['rank']==1.0].iloc[:,:2]
d_5i=d_5i[d_5i['rank']==1.0].iloc[:,:2]
d_6i=d_6i[d_6i['rank']==1.0].iloc[:,:2]
d_7i=d_7i[d_7i['rank']==1.0].iloc[:,:2]
d_8i=d_8i[d_8i['rank']==1.0].iloc[:,:2]

In [ ]:
d_1i = d_1i.rename(columns={'구매시간':'구매시간_1'})
d_2i = d_2i.rename(columns={'구매시간':'구매시간_2'})
d_3i = d_3i.rename(columns={'구매시간':'구매시간_3'})
d_4i = d_4i.rename(columns={'구매시간':'구매시간_4'})
d_5i = d_5i.rename(columns={'구매시간':'구매시간_5'})
d_6i = d_6i.rename(columns={'구매시간':'구매시간_6'})
d_7i = d_7i.rename(columns={'구매시간':'구매시간_7'})
d_8i = d_8i.rename(columns={'구매시간':'구매시간_8'})

In [ ]:
import pandas as pd
m_1= pd.merge(d_1i, d_2i, on ='점포코드', how='outer')
m_1= pd.merge(m_1, d_3i, on ='점포코드', how='outer')
m_1= pd.merge(m_1, d_4i, on ='점포코드', how='outer')
m_1= pd.merge(m_1, d_5i, on ='점포코드', how='outer')
m_1= pd.merge(m_1, d_6i, on ='점포코드', how='outer')
m_1= pd.merge(m_1, d_7i, on ='점포코드', how='outer')
m_1= pd.merge(m_1, d_8i, on ='점포코드', how='outer')
m_1

     점포코드 구매시간_1 구매시간_2 구매시간_3 구매시간_4 구매시간_5 구매시간_6 구매시간_7 구매시간_8
0      A1     17     19     16     13     16     16     16     16
1     A12     16     16     16     17     16     19     18     18
2      A2     16     15     15     15     16     17     16     15
3     A20     16     15     16     16     16     16     17     17
4     A24     18     19     18     18     16     19     15     17
..    ...    ...    ...    ...    ...    ...    ...    ...    ...
158    D8     16     21     20     13     19     11     14     10
159  C401    NaN     18     14     12     18     18     11     19
160  C476    NaN     11     14     19     19     11     12     15
161  C573    NaN     22     19     11     19     11     11     11
162    D4    NaN     23     19     23     22     20     22     22

[163 rows x 9 columns]

#### <최종 최다 판매 시간 구하기>

In [ ]:
m_1.isnull().sum()
m_1= m_1.fillna(method='ffill')
m_1

     점포코드 구매시간_1 구매시간_2 구매시간_3 구매시간_4 구매시간_5 구매시간_6 구매시간_7 구매시간_8
0      A1     17     19     16     13     16     16     16     16
1     A12     16     16     16     17     16     19     18     18
2      A2     16     15     15     15     16     17     16     15
3     A20     16     15     16     16     16     16     17     17
4     A24     18     19     18     18     16     19     15     17
..    ...    ...    ...    ...    ...    ...    ...    ...    ...
158    D8     16     21     20     13     19     11     14     10
159  C401     16     18     14     12     18     18     11     19
160  C476     16     11     14     19     19     11     12     15
161  C573     16     22     19     11     19     11     11     11
162    D4     16     23     19     23     22     20     22     22

[163 rows x 9 columns]

In [ ]:
m_1.to_csv("최다판매시간.csv", index = False)

### 2.1최소 판매 시간

In [ ]:
#기존 pd.merge
import pandas as pd
d_f = pd.DataFrame()
d_f = pd.merge(demo_1, final_df, on ='고객번호')
d_flist = pd.merge(d_f, f_list, on ='소분류코드')
d_list = pd.merge(d_flist, final_list, on ='점포코드')
fd_f = pd.merge(final_t, d_list, on ='소분류코드')
fd_f

,소분류코드,소분류명,고객번호,성별,연령대,제휴사,점포코드,구매시간,구매금액,년도,월,분기,중분류명_재,대분류명_재,시군구
0,A010101,위생세제,1,M,60세이상,A,A12,15,9500,2014,2,1st,위생용품,일상용품,강남구
1,A010101,위생세제,1,M,60세이상,A,A12,15,5000,2014,9,3rd,위생용품,일상용품,강남구
2,A010101,위생세제,1,M,60세이상,A,A12,11,19810,2014,1,1st,위생용품,일상용품,강남구
3,A010101,위생세제,1,M,60세이상,A,A12,12,1000,2015,3,5th,위생용품,일상용품,강남구
4,A010101,위생세제,1,M,60세이상,A,A12,17,6800,2015,11,8th,위생용품,일상용품,강남구
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8336524,D080401,일반네일/케어류,16424,M,25세~29세,D,D8,19,8000,2015,8,7th,미용용품,일상용품,중랑구
8336525,D080401,일반네일/케어류,18977,F,20세~24세,D,D8,19,55000,2014,8,3rd,미용용품,일상용품,중랑구
8336526,D080401,일반네일/케어류,18977,F,20세~24세,D,D8,12,3700,2015,6,6th,미용용품,일상용품,중랑구
8336527,D080401,일반네일/케어류,18977,F,20세~24세,D,D8,12,12000,2015,6,6th,미용용품,일상용품,중랑구
8336528,D080401,일반네일/케어류,18986,F,20세~24세,D,D8,14,13500,2015,9,7th,미용용품,일상용품,중랑구

In [ ]:
#타입바꾸기
fd_f["구매시간"] = fd_f["구매시간"].astype("str")

In [ ]:
d_1 = fd_f.query("분기 == '1st'")
d_2 = fd_f.query("분기 == '2nd'")
d_3 = fd_f.query("분기 == '3rd'")
d_4 = fd_f.query("분기 == '4th'")
d_5 = fd_f.query("분기 == '5th'")
d_6 = fd_f.query("분기 == '6th'")
d_7 = fd_f.query("분기 == '7th'")
d_8 = fd_f.query("분기 == '8th'")

In [ ]:
d_1f=d_1.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_2f=d_2.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_3f=d_3.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_4f=d_4.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_5f=d_5.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_6f=d_6.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_7f=d_7.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
d_8f=d_8.groupby(["점포코드","구매시간"])[['소분류명']].count().reset_index()
# d_1f[:50]

In [ ]:
d_1f['rank'] = d_1f.groupby(["점포코드"])[['소분류명']].rank(method='min', ascending=True)
d_2f['rank'] = d_2f.groupby(["점포코드"])[['소분류명']].rank(method='min', ascending=True)
d_3f['rank'] = d_3f.groupby(["점포코드"])[['소분류명']].rank(method='min', ascending=True)
d_4f['rank'] = d_4f.groupby(["점포코드"])[['소분류명']].rank(method='min', ascending=True)
d_5f['rank'] = d_5f.groupby(["점포코드"])[['소분류명']].rank(method='min', ascending=True)
d_6f['rank'] = d_6f.groupby(["점포코드"])[['소분류명']].rank(method='min', ascending=True)
d_7f['rank'] = d_7f.groupby(["점포코드"])[['소분류명']].rank(method='min', ascending=True)
d_8f['rank'] = d_8f.groupby(["점포코드"])[['소분류명']].rank(method='min', ascending=True)

In [ ]:
d_1f=d_1f[d_1f['rank']==1.0].iloc[:,:2]
d_2f=d_2f[d_2f['rank']==1.0].iloc[:,:2]
d_3f=d_3f[d_3f['rank']==1.0].iloc[:,:2]
d_4f=d_4f[d_4f['rank']==1.0].iloc[:,:2]
d_5f=d_5f[d_5f['rank']==1.0].iloc[:,:2]
d_6f=d_6f[d_6f['rank']==1.0].iloc[:,:2]
d_7f=d_7f[d_7f['rank']==1.0].iloc[:,:2]
d_8f=d_8f[d_8f['rank']==1.0].iloc[:,:2]

In [ ]:
d_1f = d_1f.rename(columns={'구매시간':'구매시간_1'})
d_2f = d_2f.rename(columns={'구매시간':'구매시간_2'})
d_3f = d_3f.rename(columns={'구매시간':'구매시간_3'})
d_4f = d_4f.rename(columns={'구매시간':'구매시간_4'})
d_5f = d_5f.rename(columns={'구매시간':'구매시간_5'})
d_6f = d_6f.rename(columns={'구매시간':'구매시간_6'})
d_7f = d_7f.rename(columns={'구매시간':'구매시간_7'})
d_8f = d_8f.rename(columns={'구매시간':'구매시간_8'})
d_8f

     점포코드 구매시간_8  소분류명  rank
0      A1      1     6   7.0
1      A1     10   726  11.0
2      A1     11  2533  13.0
3      A1     12  4621  15.0
4      A1     13  4762  18.0
...   ...    ...   ...   ...
2253   D8     19    17   7.0
2254   D8     20     3   1.0
2255   D8     21    19  10.0
2256   D8     22    10   4.0
2257   D8      9     3   1.0

[2258 rows x 4 columns]

In [ ]:
import pandas as pd
n_1= pd.merge(d_1f, d_2f, on ='점포코드' )
n_1= pd.merge(n_1, d_3f, on ='점포코드' )
n_1= pd.merge(n_1, d_4f, on ='점포코드' )
n_1= pd.merge(n_1, d_5f, on ='점포코드' )
n_1= pd.merge(n_1, d_6f, on ='점포코드' )
n_1= pd.merge(n_1, d_7f, on ='점포코드')
n_1= pd.merge(n_1, d_8f, on ='점포코드')
n_1

    점포코드 구매시간_1 구매시간_2 구매시간_3 구매시간_4 구매시간_5 구매시간_6 구매시간_7 구매시간_8
0     A1      1     22      0      2      4      1      2     22
1     A1      1     22      0      2      4      1      2      6
2     A1      1     22      0      2      4      1      2      7
3     A1      1     22      0      2      4      1      3     22
4     A1      1     22      0      2      4      1      3      6
..   ...    ...    ...    ...    ...    ...    ...    ...    ...
795   D7      2      1      3      1      2      4      2      0
796   D7      2      1      3      1      8      1      2      0
797   D7      2      1      3      1      8      4      2      0
798   D8      9      9     23      0      0      2      9     20
799   D8      9      9     23      0      0      2      9      9

[800 rows x 9 columns]

In [ ]:
import pandas as pd
n_1= pd.merge(d_1f, d_2f, on ='점포코드', how='outer')
n_1= pd.merge(n_1, d_3f, on ='점포코드', how='outer')
n_1= pd.merge(n_1, d_4f, on ='점포코드', how='outer')
n_1= pd.merge(n_1, d_5f, on ='점포코드', how='outer')
n_1= pd.merge(n_1, d_6f, on ='점포코드', how='outer')
n_1= pd.merge(n_1, d_7f, on ='점포코드', how='outer')
n_1= pd.merge(n_1, d_8f, on ='점포코드', how='outer')
n_1

    점포코드 구매시간_1 구매시간_2 구매시간_3 구매시간_4 구매시간_5 구매시간_6 구매시간_7 구매시간_8
0     A1      1     22      0      2      4      1      2     22
1     A1      1     22      0      2      4      1      2      6
2     A1      1     22      0      2      4      1      2      7
3     A1      1     22      0      2      4      1      3     22
4     A1      1     22      0      2      4      1      3      6
..   ...    ...    ...    ...    ...    ...    ...    ...    ...
795   D7      2      1      3      1      2      4      2      0
796   D7      2      1      3      1      8      1      2      0
797   D7      2      1      3      1      8      4      2      0
798   D8      9      9     23      0      0      2      9     20
799   D8      9      9     23      0      0      2      9      9

[800 rows x 9 columns]